# Generated by Django 4.0.5 on 2022-09-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('role', models.TextField()),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
    ]
