# Generated by Django 4.0.5 on 2022-09-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_service_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='resume',
            field=models.FileField(default='', upload_to='polls/files'),
        ),
    ]
