# Generated by Django 4.0.5 on 2022-09-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='service',
            name='skill',
            field=models.CharField(default='', max_length=111),
        ),
        migrations.AddField(
            model_name='service',
            name='width',
            field=models.CharField(default='', max_length=111),
        ),
    ]
