# Generated by Django 4.0.5 on 2022-09-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_message_project_remove_skill_id_skill_sno'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
